// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Registro nuevo usuario', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Registro nuevo usuario', async function() {
    await driver.get("http://localhost/InventoryApp%20Ver2-7/")
    await driver.manage().window().setRect({ width: 1382, height: 784 })
    await driver.findElement(By.linkText("Regístrate")).click()
    await driver.findElement(By.id("usuario")).sendKeys("sheiry.leal")
    await driver.findElement(By.id("password")).sendKeys("12345")
    await driver.findElement(By.id("nombre")).click()
    await driver.findElement(By.id("nombre")).sendKeys("JAVIER ENRRIQUE")
    await driver.findElement(By.id("apellido")).click()
    await driver.findElement(By.id("apellido")).sendKeys("PORRAS BEJARANO")
    await driver.findElement(By.css(".panel-body")).click()
    await driver.findElement(By.id("usuario")).sendKeys("javiereporras@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("javierporras")
    await driver.findElement(By.id("registro")).click()
    assert(await driver.switchTo().alert().getText() == "Agregado con exito")
    await driver.findElement(By.linkText("Regresar")).click()
  })
})
