// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('exploratoriolink', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('exploratoriolink', async function() {
    // Test name: exploratoriolink
    // Step # | name | target | value
    // 1 | open | http://localhost/InventoryApp%20Ver2-7/ | 
    await driver.get("http://localhost/InventoryApp%20Ver2-7/")
    // 2 | setWindowSize | 1382x784 | 
    await driver.manage().window().setRect({ width: 1382, height: 784 })
    // 3 | click | linkText=¿Quiénes somos? | 
    await driver.findElement(By.linkText("¿Quiénes somos?")).click()
    // 4 | click | css=.type > li:nth-child(2) > a | 
    await driver.findElement(By.css(".type > li:nth-child(2) > a")).click()
    // 5 | click | css=.type > li:nth-child(3) > a | 
    await driver.findElement(By.css(".type > li:nth-child(3) > a")).click()
    // 6 | click | linkText=PC ESCRITORIO | 
    await driver.findElement(By.linkText("PC ESCRITORIO")).click()
    // 7 | click | css=li:nth-child(4) > .page-scroll | 
    await driver.findElement(By.css("li:nth-child(4) > .page-scroll")).click()
    // 8 | click | css=li:nth-child(5) > .page-scroll | 
    await driver.findElement(By.css("li:nth-child(5) > .page-scroll")).click()
    // 9 | click | linkText=Servicios | 
    await driver.findElement(By.linkText("Servicios")).click()
    // 10 | click | css=li:nth-child(5) > a | 
    await driver.findElement(By.css("li:nth-child(5) > a")).click()
    // 11 | click | linkText=Regístrate | 
    await driver.findElement(By.linkText("Regístrate")).click()
    // 12 | type | id=usuario | admin
    await driver.findElement(By.id("usuario")).sendKeys("admin")
    // 13 | type | id=password | 12345
    await driver.findElement(By.id("password")).sendKeys("12345")
    // 14 | mouseDown | linkText=Regresar | 
    {
      const element = await driver.findElement(By.linkText("Regresar"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 15 | mouseUp | css=#grupo__password > .formulario__input-error | 
    {
      const element = await driver.findElement(By.css("#grupo__password > .formulario__input-error"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 16 | click | id=frmRegistro | 
    await driver.findElement(By.id("frmRegistro")).click()
    // 17 | click | linkText=Regresar | 
    await driver.findElement(By.linkText("Regresar")).click()
    // 18 | click | linkText=Clientes | 
    await driver.findElement(By.linkText("Clientes")).click()
    // 19 | type | id=usuario | admin
    await driver.findElement(By.id("usuario")).sendKeys("admin")
    // 20 | type | id=password | 12345
    await driver.findElement(By.id("password")).sendKeys("12345")
    // 21 | click | id=volver | 
    await driver.findElement(By.id("volver")).click()
  })
})
