// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('video2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('video2', async function() {
    await driver.get("http://localhost/InventoryApp%20Ver2-7/")
    await driver.manage().window().setRect({ width: 746, height: 711 })
    await driver.findElement(By.css(".navbar-toggler-icon")).click()
    await driver.findElement(By.css(".col-auto:nth-child(2) .bxl-linkedin")).click()
    await driver.executeScript("window.scrollTo(0,11)")
    await driver.executeScript("window.scrollTo(0,254)")
  })
})
