// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Inicio_sesion_admin', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Inicio_sesion_admin', async function() {
    await driver.get("http://localhost/InventoryApp%20Ver2-7/")
    await driver.manage().window().setRect({ width: 746, height: 711 })
    await driver.findElement(By.linkText("Empleados")).click()
    await driver.findElement(By.id("usuario")).sendKeys("sheiry.leal")
    await driver.findElement(By.id("password")).sendKeys("12345")
    await driver.findElement(By.css(".panel-body")).click()
    await driver.findElement(By.id("usuario")).sendKeys("admin")
    await driver.findElement(By.id("entrarSistema")).click()
    await driver.findElement(By.linkText("Usuario: admin")).click()
    await driver.findElement(By.linkText("Salir")).click()
    await driver.findElement(By.id("usuario")).sendKeys("admin")
    await driver.findElement(By.id("password")).sendKeys("12345")
  })
})
