// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Inicio_sesion_cliente', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Inicio_sesion_cliente', async function() {
    await driver.get("http://localhost/InventoryApp%20Ver2-7/")
    await driver.manage().window().setRect({ width: 746, height: 711 })
    await driver.findElement(By.linkText("Clientes")).click()
    await driver.findElement(By.linkText("Clientes")).click()
    await driver.findElement(By.id("entrarSistema")).click()
    await driver.findElement(By.linkText("Tecnologia")).click()
    await driver.findElement(By.linkText("Nuevo")).click()
    await driver.findElement(By.linkText("Usado")).click()
    await driver.findElement(By.linkText("Celulares")).click()
    await driver.findElement(By.linkText("Portátiles")).click()
    await driver.findElement(By.linkText("Pc")).click()
    await driver.findElement(By.linkText("Repuestos")).click()
    await driver.findElement(By.linkText("Accesorios")).click()
    await driver.findElement(By.linkText("Salir")).click()
  })
})
